name: cloudamountapp
description: A new Flutter project.

publish_to: 'none'

version: 0.1.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  
  bloc: ^7.1.0
  excel: ^2.0.0-null-safety-3
  equatable: ^2.0.3
  flutter_bloc: ^7.2.0
  pdf: ^3.5.0
  get_it: ^7.2.0
  path_provider: ^2.0.3
  dartz: ^0.10.0
  animations: ^2.0.1
  date_field: ^2.0.1
  path: ^1.8.0
  open_file: ^3.2.1
  permission_handler: ^8.1.4+2
  firebase_core: ^1.6.0
  cloud_firestore: ^2.5.1


dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg