name: cloudamountapp
description: A new Flutter project.

publish_to: 'none'

version: 1.1.0+2

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  easy_localization: ^3.0.0
  dart_date: ^1.1.1

  bloc: ^8.0.2
  flutter_bloc: ^8.0.1
  
  excel: ^2.0.0-null-safety-3
  pdf: ^3.6.5
  open_file: ^3.2.1
  path_provider: ^2.0.8
  permission_handler: ^8.3.0

  flutter_modular: ^4.4.0
  multiple_result: ^1.0.4
  
  animations: ^2.0.2
  flex_color_scheme: ^4.2.0

  flutter_form_builder: ^7.0.0
  form_builder_validators: ^7.3.0

  firebase_core: ^1.12.0
  cloud_firestore: ^3.1.7
  

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.4
  flutter_native_splash: ^2.0.1+1

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/translations/

